name: qmuli
version: "0.1.0"
synopsis: EDSL for building infrastructure on AWS
description: EDSL for building infrastructure on AWS
category: AWS, Cloud
maintainer: Alex Babkin
stability: experimental
license: MIT
license-file: LICENSE.md

github: qmuli/qmuli

extra-source-files:
  - CHANGELOG.md
  - README.md
  - stack.yaml


library:
  source-dirs:
    - src
  exposed-modules:
    - Qi
    - Qi.Config.AWS
    - Qi.Config.AWS.ApiGw
    - Qi.Config.AWS.CF
    - Qi.Config.AWS.CW
    - Qi.Config.AWS.DDB
    - Qi.Config.AWS.Lambda
    - Qi.Config.AWS.ApiGw.ApiMethod.Profile
    - Qi.Config.AWS.S3
    - Qi.Config.CF
    - Qi.Config.Identifier
    - Qi.Program.Lambda.Interface
    - Qi.Program.Config.Interface
    - Qi.Util
    - Qi.Util.ApiGw
    - Qi.Util.Cognito
    - Qi.Util.CustomCFResource
    - Qi.Util.DDB
    - Qi.Program.Config.Interpreters.Build
  dependencies:
    - aeson >= 1.2.1 && < 1.3
    - aeson-pretty >= 0.8.5 && < 0.9
    - amazonka >= 1.4.5 && < 1.5
    - amazonka-cloudformation >= 1.4.5 && < 1.5
    - amazonka-cloudwatch-logs >= 1.4.5 && < 1.5
    - amazonka-cognito-identity >= 1.4.5 && < 1.5
    - amazonka-cognito-idp >= 1.4.5 && < 1.5
    - amazonka-core >= 1.4.5 && < 1.5
    - amazonka-dynamodb >= 1.4.5 && < 1.5
    - amazonka-iam >= 1.4.5 && < 1.5
    - amazonka-lambda >= 1.4.5 && < 1.5
    - amazonka-s3 >= 1.4.5 && < 1.5
    - amazonka-s3-streaming >= 0.2 && < 0.3
    - base >= 4.8 && < 5
    - binary >= 0.8 && < 0.9
    - bytestring >= 0.10 && < 0.11
    - conduit >= 1.2 && < 1.3
    - conduit-extra >= 1.1 && < 1.2
    - data-default >= 0.7 && < 0.8
    - directory >= 1.3 && < 1.4
    - either >= 4.4 && < 4.5
    - exceptions >= 0.8 && < 0.9
    - executable-path >= 0.0.3 && < 0.1
    - jwt >= 0.7 && < 0.8
    - hashable >= 1.2 && < 1.3
    - heredoc >= 0.2 && < 0.3
    - http-client >= 0.5 && < 0.6
    - http-client-tls >= 0.3 && < 0.4
    - lens >= 4.15 && < 4.16
    - lens-aeson >= 1.0 && < 1.1
    - mtl >= 2.2 && < 2.3
    - text >= 1.2 && < 1.3
    - time >= 1.6 && < 1.7
    - transformers >= 0.5 && < 0.6
    - transformers-base >= 0.4 && < 0.5
    - operational >= 0.2 && < 0.3
    - process >= 1.4 && < 1.5
    - resourcet >= 1.1 && < 1.2
    - safe >= 0.3 && < 0.4
    - stm >= 2.3 && < 2.5
    - stratosphere >= 0.7 && < 0.8
    - system-extra >= 0.1 && < 0.2
    - turtle >= 1.3 && < 1.4
    - unix >= 2.7 && < 2.8
    - unordered-containers >= 0.2 && < 0.3
    - yaml >= 0.8 && < 0.9
    - extra >= 1.5 && < 1.6
    - ansi-terminal >= 0.6 && < 0.7

flags:
  build-examples:
    description: "Skip building examples"
    default: false
    manual: true


executables:
  qmuli-simple-s3-copy:
    main: Main.hs
    source-dirs: examples/simple-s3-copy/src
    dependencies:
      - base >= 4.8 && < 5
      - qmuli
    when:    
    - condition: flag(build-examples)
      then:
        buildable: true
      else:
        buildable: false

  # qmuli-fold-s3-content:
    # main: Main.hs
    # source-dirs: examples/fold-s3-content/src
    # dependencies:
      # - base >= 4.8 && < 5
      # - qmuli
  # qmuli-stream-s3-objects:
    # main: Main.hs
    # source-dirs: examples/stream-s3-objects/src
    # dependencies:
      # - base >= 4.8 && < 5
      # - qmuli
  # qmuli-apigw-lambda-s3:
    # main: Main.hs
    # source-dirs: examples/apigw-lambda-s3/src
    # dependencies:
      # - base >= 4.8 && < 5
      # - qmuli
  # qmuli-apigw-lambda-dynamodb:
    # main: Main.hs
    # source-dirs: examples/apigw-lambda-dynamodb/src
    # dependencies:
      # - base >= 4.8 && < 5
      # - qmuli
  # qmuli-dynamodb-stream:
    # main: Main.hs
    # source-dirs: examples/dynamodb-stream/src
    # dependencies:
      # - base >= 4.8 && < 5
      # - qmuli
  # qmuli-cognito-apigw-lambda:
    # main: Main.hs
    # source-dirs: examples/cognito-apigw-lambda/src
    # dependencies:
      # - base >= 4.8 && < 5
      # - qmuli
  # qmuli-cognito-lambda:
    # main: Main.hs
    # source-dirs: examples/cognito-lambda/src
    # dependencies:
      # - base >= 4.8 && < 5
      # - qmuli
  # qmuli-cw-events:
    # main: Main.hs
    # source-dirs: examples/cw-events/src
    # dependencies:
      # - base >= 4.8 && < 5
      # - qmuli

tests:
  tasty:
    main: Main.hs
    source-dirs:
      - tests
    dependencies:
      - aeson
      - aeson-pretty
      - base
      - bytestring
      - data-default
      - heredoc
      - lens
      - lens-aeson
      - mtl
      - qmuli
      - stratosphere
      - tasty
      - tasty-hspec
      - text
      - unordered-containers
