name: qmuli
version: "0.1.0"
synopsis: EDSL for building infrastructure on AWS
description: EDSL for building infrastructure on AWS
category: AWS, Cloud
maintainer: Alex Babkin
stability: experimental
license: MIT
license-file: LICENSE.md

github: qmuli/qmuli

extra-source-files:
  - CHANGELOG.md
  - README.md
  - stack.yaml

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings

dependencies:
  - aeson
  - aeson-pretty
  - amazonka
  - amazonka-cloudformation
  - amazonka-cloudwatch-logs
  - amazonka-cognito-identity
  - amazonka-cognito-idp
  - amazonka-core
  - amazonka-dynamodb
  - amazonka-iam
  - amazonka-lambda
  - amazonka-s3
  #- amazonka-s3-streaming
  - base
  - binary
  - bytestring
  - conduit
  - conduit-extra
  - data-default
  - directory
  - either
  - exceptions
  - executable-path
  - jwt
  - hashable
  - heredoc
  - http-client
  - http-client-tls
  - lens
  - lens-aeson
  - mtl
  - protolude
  - text
  - time
  - transformers
  - transformers-base
  - operational
  - optparse-applicative
  - process
  - protolude
  - resourcet
  - safe
  - stm
  - stratosphere
  - system-extra
  - turtle
  - unix
  - unordered-containers
  - yaml
  - extra
  - ansi-terminal


library:
  source-dirs:
    - src
  exposed-modules:
    - Qi
    - Qi.Options
    - Qi.Config.AWS
    - Qi.Config.AWS.ApiGw
    - Qi.Config.AWS.CF
    - Qi.Config.AWS.CW
    - Qi.Config.AWS.DDB
    - Qi.Config.AWS.Lambda
    - Qi.Config.AWS.ApiGw.ApiMethod.Profile
    - Qi.Config.AWS.S3
    - Qi.Config.CF
    - Qi.Config.Identifier
    - Qi.Core.Curry
    - Qi.Program.Lambda.Interface
    - Qi.Program.Config.Interface
    - Qi.Util
    - Qi.Util.ApiGw
    - Qi.Util.Cognito
    - Qi.Util.CustomCFResource
    - Qi.Util.DDB
    - Qi.Program.Config.Interpreters.Build

flags:
  build-examples:
    description: "Build examples"
    default: true
    manual: true


executables:
  qmuli-simple-s3-copy:
    main: Main.hs
    source-dirs: examples/simple-s3-copy/src
    dependencies:
      - base
      - qmuli
    when:    
    - condition: flag(build-examples)
      then:
        buildable: true
      else:
        buildable: false

        #  qmuli-fold-s3-content:
        #    main: Main.hs
        #    source-dirs: examples/fold-s3-content/src
        #    dependencies:
        #      - base
        #      - qmuli
        #    when:    
        #    - condition: flag(build-examples)
        #      then:
        #        buildable: true
        #      else:
        #        buildable: false


  # qmuli-stream-s3-objects:
    # main: Main.hs
    # source-dirs: examples/stream-s3-objects/src
    # dependencies:
      # - base >= 4.8 && < 5
      # - qmuli
  # qmuli-apigw-lambda-s3:
    # main: Main.hs
    # source-dirs: examples/apigw-lambda-s3/src
    # dependencies:
      # - base >= 4.8 && < 5
      # - qmuli
  # qmuli-apigw-lambda-dynamodb:
    # main: Main.hs
    # source-dirs: examples/apigw-lambda-dynamodb/src
    # dependencies:
      # - base >= 4.8 && < 5
      # - qmuli
  # qmuli-dynamodb-stream:
    # main: Main.hs
    # source-dirs: examples/dynamodb-stream/src
    # dependencies:
      # - base >= 4.8 && < 5
      # - qmuli
  # qmuli-cognito-apigw-lambda:
    # main: Main.hs
    # source-dirs: examples/cognito-apigw-lambda/src
    # dependencies:
      # - base >= 4.8 && < 5
      # - qmuli
  # qmuli-cognito-lambda:
    # main: Main.hs
    # source-dirs: examples/cognito-lambda/src
    # dependencies:
      # - base >= 4.8 && < 5
      # - qmuli

  qmuli-cw-events:
    main: Main.hs
    source-dirs: examples/cw-events/src
    dependencies:
      - base
      - qmuli
    when:
    - condition: flag(build-examples)
      then:
        buildable: true
      else:
        buildable: false
tests:
  tasty:
    main: Main.hs
    source-dirs:
      - tests
    dependencies:
      - qmuli
      - tasty
      - tasty-hspec
      - text
      - unordered-containers
