resolver: nightly-2018-06-23

packages:
- '.'
- location:
    git: https://github.com/ababkin/system-extra.git
    commit: 8f3f93d5172744a8dedde57693c2b5d3c15f745c
  extra-dep: true
  #- location:
  #  git: https://github.com/ababkin/amazonka-s3-streaming.git
  #  commit: 4fc25d1b20007bef3b8b2924751fe0fc3033e1f5
  #extra-dep: true
- location:
    git: https://github.com/ababkin/amazonka.git
    commit: 248f7b2a7248222cc21cef6194cd1872ba99ac5d
    subdirs:
    - amazonka
    - amazonka-lex-models
    - core
  extra-dep: true

extra-deps: []
  
flags: {}

extra-package-dbs: []

ghc-options:
  "qmuli": 
    # -O*
    # -funfolding-use-threshold=16 -O2 -optc-O3
    -O0
    -Wall
    -Wno-unused-imports 
    -Wno-unused-matches 
    -Wno-unused-do-bind
    -Wno-deprecations
    -threaded
    -Werror
    #-static 

    # "qmuli-stream-s3-objects": -static -threaded
    # "qmuli-fold-s3-content": -static -threaded
    # "qmuli-apigw-lambda-dynamodb": -static -threaded

apply-ghc-options: locals # all local packages, the default

build:
  library-profiling: false
  executable-profiling: false
  copy-bins: false
  prefetch: false
  keep-going: false


